spring:
  application:
    name: order-service
  
  # Configuration Kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  
  # Configuration Base de donn√©es
  datasource:
    url: jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# Configuration du serveur
server:
  port: 8083

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Topics Kafka
kafka:
  topics:
    order-events: order-events

# URLs des autres services
services:
  product-service:
    url: http://localhost:8082
  customer-service:
    url: http://localhost:8086

# Logging
logging:
  level:
    com.ghali.ecommerce.order: DEBUG
